"""add Owner table and make relationship 

Revision ID: d7a81a2e88d5
Revises: 81b67efb00d1
Create Date: 2025-03-05 18:07:26.842505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a81a2e88d5'
down_revision = '81b67efb00d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id_pup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pup'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner')
    # ### end Alembic commands ###
